# Generated by Django 4.2.14 on 2024-07-16 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_eggbatch_farm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egginventory',
            name='batch_number',
        ),
    ]
