# Generated by Django 4.2.14 on 2024-07-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_egginventory_batch_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggInventory',
            name='batch_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
