# Generated by Django 4.2.14 on 2024-07-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_egginventory_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egginventory',
            name='batch_number',
            field=models.CharField(default='default_batch', max_length=100),
        ),
    ]
