# Generated by Django 4.2.14 on 2024-07-16 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_egginventory_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggbatch',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_batches', to='core.farm'),
        ),
    ]
