# Generated by Django 4.2.14 on 2024-07-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_eggbatch_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='numberOfhens',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
