# Generated by Django 4.2.14 on 2024-07-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_farm_numberofhens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseinventory',
            name='unitPrice',
            field=models.IntegerField(),
        ),
    ]
